QBShared = QBShared or {}
-- Vehicles
QBShared.Vehicles = {
	--- Compacts
	['hggrpo'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' YARIS GR polsICE ',
		['brand'] = 'HONDA',
		['model'] = 'hggrpo',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `hggrpo`,
		['shop'] = 'pdm',
	},
	['hgevo10po'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' EVO 10 POLICE ',
		['brand'] = 'HONDA',
		['model'] = 'hgevo10po',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `hgevo10po`,
		['shop'] = 'pdm',
	},
	['tempesta2'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' LAMBORGHINI TEMPESTA ',
		['brand'] = 'LAMBO',
		['model'] = 'tempesta2',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `tempesta2`,
		['shop'] = 'pdm',
	},
	['tractorc'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' Tracktor RC 1 ',
		['brand'] = 'Tracktor',
		['model'] = 'tractorc',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `tractorc`,
		['shop'] = 'pdm',
	},
	['tractorcv8'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' Tracktor RC 2 ',
		['brand'] = 'Tracktor',
		['model'] = 'tractorcv8',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `tractorcv8`,
		['shop'] = 'pdm',
	},
	['tsgr20'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' Supra MK5 ',
		['brand'] = 'Toyota',
		['model'] = 'tsgr20',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `tsgr20`,
		['shop'] = 'pdm',
	},
	['ucballer'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' Ballen Unmarked ',
		['brand'] = 'locals',
		['model'] = 'ucballer',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `ucballer`,
		['shop'] = 'pdm',
	},
	['ucbanshee'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' Banshee Unmarked ',
		['brand'] = 'locals',
		['model'] = 'ucbanshee',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `ucbanshee`,
		['shop'] = 'pdm',
	},
	['ucbuffalo'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' Buffalo Unmarked ',
		['brand'] = 'locals',
		['model'] = 'ucbuffalo',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `ucbuffalo`,
		['shop'] = 'pdm',
	},
	['uccomet'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' Comet Unmarked ',
		['brand'] = 'locals',
		['model'] = 'uccomet',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `uccomet`,
		['shop'] = 'pdm',
	},
	['uccoquette'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' Coquette Unmarked ',
		['brand'] = 'locals',
		['model'] = 'uccoquette',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `uccoquette`,
		['shop'] = 'pdm',
	},
	['ucprimo'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' Primo Unmarked ',
		['brand'] = 'locals',
		['model'] = 'ucprimo',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `ucprimo`,
		['shop'] = 'pdm',
	},
	['ucrancher'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' Rancher Unmarked ',
		['brand'] = 'locals',
		['model'] = 'ucrancher',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `ucrancher`,
		['shop'] = 'pdm',
	},
	['ucwashington'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' Washington Unmarked ',
		['brand'] = 'locals',
		['model'] = 'ucwashington',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `ucwashington`,
		['shop'] = 'pdm',
	},
	['unicycle'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' UNI CYCLE ',
		['brand'] = 'Bycycle',
		['model'] = 'unicycle',
		['price'] = 221000, 	
		['category'] = 'motors',
		['hash'] = `unicycle`,
		['shop'] = 'pdm',
	},
	['victor'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' Victor',
		['brand'] = 'locals',
		['model'] = 'victor',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `victor`,
		['shop'] = 'pdm',
	},
	['vustretch'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' Vustretch',
		['brand'] = 'locals',
		['model'] = 'vustretch',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `vustretch`,
		['shop'] = 'pdm',
	},
	['vuwashington'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' vuwashington',
		['brand'] = 'locals',
		['model'] = 'vuwashington',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `vuwashington`,
		['shop'] = 'pdm',
	},
	['yosemite6str'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' Yosmite 6 STR',
		['brand'] = 'locals',
		['model'] = 'yosemite6str',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `yosemite6str`,
		['shop'] = 'pdm',
	},
	['z190custom'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' z190 Custom',
		['brand'] = 'locals',
		['model'] = 'z190custom',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `z190custom`,
		['shop'] = 'pdm',
	},
	['z2879'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' z2879 Custom',
		['brand'] = 'locals',
		['model'] = 'z2879',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `z2879`,
		['shop'] = 'pdm',
	},
	['zr3806str'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' ZR380 STR',
		['brand'] = 'locals',
		['model'] = 'zr3806str',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `zr3806str`,
		['shop'] = 'pdm',
	},
	['zx10'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' ZX10',
		['brand'] = 'motors',
		['model'] = 'zx10',
		['price'] = 221000, 	
		['category'] = 'motors',
		['hash'] = `zx10`,
		['shop'] = 'pdm',
	},
	['revolution6str2'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = ' Recvolution 6 STR',
		['brand'] = 'locals',
		['model'] = 'revolution6str2',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `revolution6str2`,
		['shop'] = 'pdm',
	},
	['rmodmustang'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Rmod Mustang',
		['brand'] = 'Mustang',
		['model'] = 'rmodmustang',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `rmodmustang`,
		['shop'] = 'pdm',
	},
	['rr14'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Range Rover 14',
		['brand'] = 'Range Rover',
		['model'] = 'rr14',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `rr14`,
		['shop'] = 'pdm',
	},
	['rudiharley'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Harley Rudi',
		['brand'] = 'harley',
		['model'] = 'rudiharley',
		['price'] = 221000, 	
		['category'] = 'motors',
		['hash'] = `rudiharley`,
		['shop'] = 'pdm',
	},
	['ruiner6str'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Ruiner STR',
		['brand'] = 'locals',
		['model'] = 'ruiner6str',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `ruiner6str`,
		['shop'] = 'pdm',
	},
	['rumpo2'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Rumpo',
		['brand'] = 'locals',
		['model'] = 'rumpo2',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `rumpo2`,
		['shop'] = 'pdm',
	},
	['s15rb'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Siliva 15 rb',
		['brand'] = 'Nissan',
		['model'] = 's15rb',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `s15rb`,
		['shop'] = 'pdm',
	},
	['savanna'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Cyber Truck',
		['brand'] = 'Truck',
		['model'] = 'savanna',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `savanna`,
		['shop'] = 'pdm',
	},
	['schwarzer2'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Schawrzer',
		['brand'] = 'locals',
		['model'] = 'schwarzer2',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `schwarzer2`,
		['shop'] = 'pdm',
	},
	['senna'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Maclaren Senna',
		['brand'] = 'Macralen',
		['model'] = 'senna',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `senna`,
		['shop'] = 'pdm',
	},
	['sentinel6str'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Sentinel STR',
		['brand'] = 'locals',
		['model'] = 'sentinel6str',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `sentinel6str`,
		['shop'] = 'pdm',
	},
	['sentinel6str2'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Sentinel 2 STR',
		['brand'] = 'locals',
		['model'] = 'sentinel6str2',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `sentinel6str2`,
		['shop'] = 'pdm',
	},
	['sentinelsg4'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Sentinel 4',
		['brand'] = 'locals',
		['model'] = 'sentinelsg4',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `sentinelsg4`,
		['shop'] = 'pdm',
	},
	['skart'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Skart',
		['brand'] = 'locals',
		['model'] = 'skart',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `skart`,
		['shop'] = 'pdm',
	},
	['skart'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Skart',
		['brand'] = 'Skart',
		['model'] = 'skart',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `skart`,
		['shop'] = 'pdm',
	},
	['srt8b'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'JEEP SRT',
		['brand'] = 'JEEP',
		['model'] = 'srt8b',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `srt8b`,
		['shop'] = 'pdm',
	},
	['starone'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Startone',
		['brand'] = 'Stat',
		['model'] = 'starone',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `starone`,
		['shop'] = 'pdm',
	},
	['stratumc'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Stratum',
		['brand'] = 'Star',
		['model'] = 'stratumc',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `stratumc`,
		['shop'] = 'pdm',
	},
	['subwrx'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Subaru WRX',
		['brand'] = 'Subaru',
		['model'] = 'subwrx',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `subwrx`,
		['shop'] = 'pdm',
	},
	['sultanrsv8'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Sultan RS Custom',
		['brand'] = 'locals',
		['model'] = 'sultanrsv8',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `sultanrsv8`,
		['shop'] = 'pdm',
	},
	['tampa5'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Drift Tampa 5',
		['brand'] = 'locals',
		['model'] = 'tampa5',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `tampa5`,
		['shop'] = 'pdm',
	},
	['taxirooster'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Taxi Rooster',
		['brand'] = 'locals',
		['model'] = 'taxirooster',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `taxirooster`,
		['shop'] = 'pdm',
	},
	['npolsexp'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Ford polsice',
		['brand'] = 'FORD',
		['model'] = 'npolsexp',
		['price'] = 221000, 	
		['category'] = 'pols',
		['hash'] = `npolsexp`,
		['shop'] = 'pdm',
	},
	['npolsmm'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'motors polsice',
		['brand'] = 'motors',
		['model'] = 'npolsmm',
		['price'] = 221000, 	
		['category'] = 'pols',
		['hash'] = `npolsmm`,
		['shop'] = 'pdm',
	},
	['npolsmm'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'motors polsice',
		['brand'] = 'motors',
		['model'] = 'npolsmm',
		['price'] = 221000, 	
		['category'] = 'pols',
		['hash'] = `npolsmm`,
		['shop'] = 'pdm',
	},
	['npolsretinue'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Retinue',
		['brand'] = 'polsice',
		['model'] = 'npolsretinue',
		['price'] = 221000, 	
		['category'] = 'pols',
		['hash'] = `npolsretinue`,
		['shop'] = 'pdm',
	},
	['npolstang'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Mustang',
		['brand'] = 'polsice',
		['model'] = 'npolstang',
		['price'] = 221000, 	
		['category'] = 'pols',
		['hash'] = `npolstang`,
		['shop'] = 'pdm',
	},
	['npolsvette'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Corvette polsice',
		['brand'] = 'polsice',
		['model'] = 'npolsvette',
		['price'] = 221000, 	
		['category'] = 'pols',
		['hash'] = `npolsvette`,
		['shop'] = 'pdm',
	},
	['npolsvic'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Sheriff polsice',
		['brand'] = 'polsice',
		['model'] = 'npolsvic',
		['price'] = 221000, 	
		['category'] = 'pols',
		['hash'] = `npolsvic`,
		['shop'] = 'pdm',
	},
	['nptaco'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'taco',
		['brand'] = 'locals',
		['model'] = 'nptaco',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `nptaco`,
		['shop'] = 'pdm',
	},
	['npwheelchair'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Wheel Chair',
		['brand'] = 'chairs',
		['model'] = 'npwheelchair',
		['price'] = 221000, 	
		['category'] = 'motors',
		['hash'] = `npwheelchair`,
		['shop'] = 'pdm',
	},
	['panamera17turbo'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Panamera 17 Turbo',
		['brand'] = 'porche',
		['model'] = 'panamera17turbo',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `panamera17turbo`,
		['shop'] = 'pdm',
	},
	['payneschaf'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Payneschaf',
		['brand'] = 'locals',
		['model'] = 'payneschaf',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `payneschaf`,
		['shop'] = 'pdm',
	},
	['penumbra3'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Penumbra',
		['brand'] = 'locals',
		['model'] = 'penumbra3',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `penumbra3`,
		['shop'] = 'pdm',
	},
	['pigalle6str'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Pigalle 6 Str',
		['brand'] = 'Lampadati',
		['model'] = 'pigalle6str',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `pigalle6str`,
		['shop'] = 'pdm',
	},
	['polsfegway'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'polsfegway ',
		['brand'] = 'motors',
		['model'] = 'polsfegway',
		['price'] = 221000, 	
		['category'] = 'pols',
		['hash'] = `polsfegway`,
		['shop'] = 'pdm',
	},
	['por930'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Porche 930 ',
		['brand'] = 'Porche',
		['model'] = 'por930',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `por930`,
		['shop'] = 'pdm',
	},
	['primoard'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Primoard',
		['brand'] = 'locals',
		['model'] = 'primoard',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `primoard`,
		['shop'] = 'pdm',
	},
	['r1'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Yamaha R1',
		['brand'] = 'Yamaha',
		['model'] = 'r1',
		['price'] = 221000, 	
		['category'] = 'motors',
		['hash'] = `r1`,
		['shop'] = 'pdm',
	},
	['r8h'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Audi R8 H',
		['brand'] = 'Audi',
		['model'] = 'r8h',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `r8h`,
		['shop'] = 'pdm',
	},
	['r8v10'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Audi R8',
		['brand'] = 'Audi',
		['model'] = 'r8v10',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `r8v10`,
		['shop'] = 'pdm',
	},
	['r32'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Nissan R32',
		['brand'] = 'Nissan',
		['model'] = 'r32',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `r32`,
		['shop'] = 'pdm',
	},
	['r35'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Nissan R35',
		['brand'] = 'Nissan',
		['model'] = 'r35',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `r35`,
		['shop'] = 'pdm',
	},
	['raid'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Raid',
		['brand'] = 'Raid',
		['model'] = 'raid',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `raid`,
		['shop'] = 'pdm',
	},
	['rcf'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Lexus RCF',
		['brand'] = 'Lexus',
		['model'] = 'rcf',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `rcf`,
		['shop'] = 'pdm',
	},
	['gtrc'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'AMG GTR C',
		['brand'] = 'Marcedes',
		['model'] = 'gtrc',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `gtrc`,
		['shop'] = 'pdm',
	},
	['hellion6str'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Helion STR',
		['brand'] = 'locals',
		['model'] = 'hellion6str',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `hellion6str`,
		['shop'] = 'pdm',
	},
	['hoabrawler'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Brawler STR',
		['brand'] = 'locals',
		['model'] = 'hoabrawler',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `hoabrawler`,
		['shop'] = 'pdm',
	},
	['hustler6str'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Hustler STR',
		['brand'] = 'locals',
		['model'] = 'hustler6str',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `hustler6str`,
		['shop'] = 'pdm',
	},
	['jester'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Jester STR',
		['brand'] = 'locals',
		['model'] = 'jester',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `jester`,
		['shop'] = 'pdm',
	},
	['kart'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'GoKart',
		['brand'] = 'locals',
		['model'] = 'kart',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `kart`,
		['shop'] = 'pdm',
	},
	['kart'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'GoKart',
		['brand'] = 'locals',
		['model'] = 'kart',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `kart`,
		['shop'] = 'pdm',
	},
	['ladybird6str'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Lady Bird STR',
		['brand'] = 'locals',
		['model'] = 'ladybird6str',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `ladybird6str`,
		['shop'] = 'pdm',
	},
	['laferrari17'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'LaFerrari 17',
		['brand'] = 'Ferrari',
		['model'] = 'laferrari17',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `laferrari17`,
		['shop'] = 'pdm',
	},
	['lc100'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'LC 100',
		['brand'] = 'Land Cruiser',
		['model'] = 'lc100',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `lc100`,
		['shop'] = 'pdm',
	},
	['lc500'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Lexus LC 500',
		['brand'] = 'Lexus',
		['model'] = 'lc500',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `lc500`,
		['shop'] = 'pdm',
	},
	['lfa'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Lexus LFA',
		['brand'] = 'Lexus',
		['model'] = 'lfa',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `lfa`,
		['shop'] = 'pdm',
	},
	['lp670'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Lamborghini LP670',
		['brand'] = 'Lamborghini',
		['model'] = 'lp670',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `lp670`,
		['shop'] = 'pdm',
	},
	['lp700'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Lamborghini LP700',
		['brand'] = 'Lamborghini',
		['model'] = 'lp700',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `lp700`,
		['shop'] = 'pdm',
	},
	['m3e46'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'BMW M3E46',
		['brand'] = 'BMW',
		['model'] = 'm3e46',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `m3e46`,
		['shop'] = 'pdm',
	},
	['m4'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'BMW M4',
		['brand'] = 'BMW',
		['model'] = 'm4',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `m4`,
		['shop'] = 'pdm',
	},
	['m5e60'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'BMW M5E60',
		['brand'] = 'BMW',
		['model'] = 'm5e60',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `m5e60`,
		['shop'] = 'pdm',
	},
	['mustang19'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'MUSTANG 19',
		['brand'] = 'MUSTANG',
		['model'] = 'mustang19',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `mustang19`,
		['shop'] = 'pdm',
	},
	['mwgranger'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Granger',
		['brand'] = 'locals',
		['model'] = 'mwgranger',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `mwgranger`,
		['shop'] = 'pdm',
	},
	['na6'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Mazda NA6',
		['brand'] = 'Mazda',
		['model'] = 'na6',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `na6`,
		['shop'] = 'pdm',
	},
	['newsvan'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'SVAN',
		['brand'] = 'locals',
		['model'] = 'newsvan',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `newsvan`,
		['shop'] = 'pdm',
	},
	['npolsblazer'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Blazzer',
		['brand'] = 'polsice',
		['model'] = 'npolsblazer',
		['price'] = 221000, 	
		['category'] = 'pols',
		['hash'] = `npolsblazer`,
		['shop'] = 'pdm',
	},
	['npolschal'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Chalangger SRT',
		['brand'] = 'polsice',
		['model'] = 'npolschal',
		['price'] = 221000, 	
		['category'] = 'pols',
		['hash'] = `npolschal`,
		['shop'] = 'pdm',
	},
	['npolschar'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Charger SRT',
		['brand'] = 'polsice',
		['model'] = 'npolschar',
		['price'] = 221000, 	
		['category'] = 'pols',
		['hash'] = `npolschar`,
		['shop'] = 'pdm',
	},
	['e36prb'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'BMW M3 E36',
		['brand'] = 'BMW',
		['model'] = 'e36prb',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `e36prb`,
		['shop'] = 'pdm',
	},
	['ellie6str'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Ellie STR',
		['brand'] = 'locals',
		['model'] = 'ellie6str',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `ellie6str`,
		['shop'] = 'pdm',
	},
	['emsnspeedo'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'EMS VAN SPEEDO',
		['brand'] = 'EMS',
		['model'] = 'emsnspeedo',
		['price'] = 221000, 	
		['category'] = 'pols',
		['hash'] = `emsnspeedo`,
		['shop'] = 'pdm',
	},
	['emsv'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'EMS VAN SPEEDO 2',
		['brand'] = 'EMS',
		['model'] = 'emsv',
		['price'] = 221000, 	
		['category'] = 'pols',
		['hash'] = `emsv`,
		['shop'] = 'pdm',
	},
	['esv'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'ESCALADE',
		['brand'] = 'EMS',
		['model'] = 'esv',
		['price'] = 221000, 	
		['category'] = 'pols',
		['hash'] = `esv`,
		['shop'] = 'pdm',
	},
	['evo9'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Lancer Evo 9',
		['brand'] = 'Mitsubishi',
		['model'] = 'evo9',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `evo9`,
		['shop'] = 'pdm',
	},
	['f10m5rc'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'RC BMW',
		['brand'] = 'BMW',
		['model'] = 'f10m5rc',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `f10m5rc`,
		['shop'] = 'pdm',
	},
	['f150'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'FORD F150',
		['brand'] = 'FORD',
		['model'] = 'f150',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `f150`,
		['shop'] = 'pdm',
	},
	['filthynsx'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Flifhty NSX',
		['brand'] = 'NSX',
		['model'] = 'filthynsx',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `filthynsx`,
		['shop'] = 'pdm',
	},
	['fk8'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Civic FK8',
		['brand'] = 'Honda',
		['model'] = 'fk8',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `fk8`,
		['shop'] = 'pdm',
	},
	['fnf4r34'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'FNF R34',
		['brand'] = 'Nissan',
		['model'] = 'fnf4r34',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `fnf4r34`,
		['shop'] = 'pdm',
	},
	['fnfrx7'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'FNF RX7',
		['brand'] = 'Mazda',
		['model'] = 'fnfrx7',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `fnfrx7`,
		['shop'] = 'pdm',
	},
	['futo3'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Futo',
		['brand'] = 'locals',
		['model'] = 'futo3',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `futo3`,
		['shop'] = 'pdm',
	},
	['dabneon'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Neon',
		['brand'] = 'locals',
		['model'] = 'dabneon',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `dabneon`,
		['shop'] = 'pdm',
	},
	['gauntlet6str'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Gauntlet STR',
		['brand'] = 'locals',
		['model'] = 'gauntlet6str',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `gauntlet6str`,
		['shop'] = 'pdm',
	},
	['deluxo2'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Deluxo2',
		['brand'] = 'locals',
		['model'] = 'deluxo2',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `deluxo2`,
		['shop'] = 'pdm',
	},
	['deluxo6str'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Deluxo STR',
		['brand'] = 'locals',
		['model'] = 'deluxo6str',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `deluxo6str`,
		['shop'] = 'pdm',
	},
	['granlb'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Maseratii GranLB',
		['brand'] = 'Maserati',
		['model'] = 'granlb',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `granlb`,
		['shop'] = 'pdm',
	},
	['demon'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Dodge Demon',
		['brand'] = 'Dodge',
		['model'] = 'demon',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `demon`,
		['shop'] = 'pdm',
	},
	['22g63'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'AMG G63',
		['brand'] = 'Marcedes',
		['model'] = '22g63',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `22g63`,
		['shop'] = 'pdm',
	},
	['66fastback'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Fast Back',
		['brand'] = 'Fast',
		['model'] = '66fastback',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `66fastback`,
		['shop'] = 'pdm',
	},
	['69charger'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Dodge Charger',
		['brand'] = 'Dodge',
		['model'] = '69charger',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `69charger`,
		['shop'] = 'pdm',
	},
	['488misha'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Ferrari 488',
		['brand'] = 'Ferrari',
		['model'] = '488misha',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `488misha`,
		['shop'] = 'pdm',
	},
	['500gtrlam'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Lambo GTR 500',
		['brand'] = 'Lamborghini',
		['model'] = '500gtrlam',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `500gtrlam`,
		['shop'] = 'pdm',
	},
	['675ltsp'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Maclaren 675',
		['brand'] = 'Maclaren',
		['model'] = '675ltsp',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `675ltsp`,
		['shop'] = 'pdm',
	},
	['720s'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Maclaren 720s',
		['brand'] = 'Maclaren',
		['model'] = '720s',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `720s`,
		['shop'] = 'pdm',
	},
	['a80'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Supra a80',
		['brand'] = 'Toyota',
		['model'] = 'a80',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `a80`,
		['shop'] = 'pdm',
	},
	['db11'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'DB 11',
		['brand'] = 'DB',
		['model'] = 'db11',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `db11`,
		['shop'] = 'pdm',
	},
	['dc5'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Honda Integra',
		['brand'] = 'Honda',
		['model'] = 'dc5',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `dc5`,
		['shop'] = 'pdm',
	},
	['delsoleg'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Civic SiR',
		['brand'] = 'Honda',
		['model'] = 'delsoleg',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `delsoleg`,
		['shop'] = 'pdm',
	},
	['gt17'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Ford GT 17',
		['brand'] = 'Ford',
		['model'] = 'gt17',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `gt17`,
		['shop'] = 'pdm',
	},
	['gt63'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'AMG GT 63',
		['brand'] = 'Marcedes',
		['model'] = 'gt63',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `gt63`,
		['shop'] = 'pdm',
	},
	['gt86'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Toyota GT 86',
		['brand'] = 'Toyota',
		['model'] = 'gt86',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `gt86`,
		['shop'] = 'pdm',
	},
	['gtr'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'GTR Coupes',
		['brand'] = 'Nissan',
		['model'] = 'gtr',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `gtr`,
		['shop'] = 'pdm',
	},
	['ap2'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'HONDA AP2',
		['brand'] = 'Honda',
		['model'] = 'ap2',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `ap2`,
		['shop'] = 'pdm',
	},
	['asbo2'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'ASBO',
		['brand'] = 'locals',
		['model'] = 'asbo2',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `asbo2`,
		['shop'] = 'pdm',
	},
	['audirs6tk'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'RS 6 STK',
		['brand'] = 'AUDI',
		['model'] = 'audirs6tk',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `audirs6tk`,
		['shop'] = 'pdm',
	},
	['banshee2fix'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Banshee2',
		['brand'] = 'locals',
		['model'] = 'banshee2fix',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `banshee2fix`,
		['shop'] = 'pdm',
	},
	['bc'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Huayra BC',
		['brand'] = 'Huayra',
		['model'] = 'bc',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `bc`,
		['shop'] = 'pdm',
	},
	['bcat'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Bcat',
		['brand'] = 'Bcat',
		['model'] = 'bcat',
		['price'] = 221000, 	
		['category'] = 'pols',
		['hash'] = `bcat`,
		['shop'] = 'pdm',
	},
	['bdragon'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Bantley Dragon',
		['brand'] = 'Banyley',
		['model'] = 'bdragon',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `bdragon`,
		['shop'] = 'pdm',
	},
	['bimx'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Bmx Custom',
		['brand'] = 'bmx',
		['model'] = 'bimx',
		['price'] = 221000, 	
		['category'] = 'motors',
		['hash'] = `bimx`,
		['shop'] = 'pdm',
	},
	['bluecunt'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Bluecunt',
		['brand'] = 'bluecunt',
		['model'] = 'bluecunt',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `bluecunt`,
		['shop'] = 'pdm',
	},
	['bmwr'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'BMR R 1000',
		['brand'] = 'BMW',
		['model'] = 'bmwr',
		['price'] = 221000, 	
		['category'] = 'motors',
		['hash'] = `bmwr`,
		['shop'] = 'pdm',
	},
	['bolide'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Buggati Bolide',
		['brand'] = 'Buggati',
		['model'] = 'bolide',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `bolide`,
		['shop'] = 'pdm',
	},
	['bt62r'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Braham BT 62R',
		['brand'] = 'Braham',
		['model'] = 'bt62r',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `bt62r`,
		['shop'] = 'pdm',
	},
	['c7'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Corvette c7',
		['brand'] = 'Corvette',
		['model'] = 'c7',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `c7`,
		['shop'] = 'pdm',
	},
	['chillybin'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Box Bike',
		['brand'] = 'motors',
		['model'] = 'chillybin',
		['price'] = 221000, 	
		['category'] = 'motors',
		['hash'] = `chillybin`,
		['shop'] = 'pdm',
	},
	['contss18'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Bantley Conts18',
		['brand'] = 'Bantley',
		['model'] = 'contss18',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `contss18`,
		['shop'] = 'pdm',
	},
	['cp9a'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Lancer CP 9 A',
		['brand'] = 'Mitsubishi',
		['model'] = 'cp9a',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `cp9a`,
		['shop'] = 'pdm',
	},
	----- CUSTOM & PATRE ___
	['c86karma_th_hwkjp9a'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'GT 86 Karma',
		['brand'] = 'Toyota',
		['model'] = '86karma_th_hwkj',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `86karma_th_hwkj`,
		['shop'] = 'pdm',
	},
	['fiestarbcamber'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'GT 86 Karma',
		['brand'] = 'Toyota',
		['model'] = 'fiestarbcamber',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `fiestarbcamber`,
		['shop'] = 'pdm',
	},
	['foxraptor'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Raptor F150 Fox',
		['brand'] = 'Ford',
		['model'] = 'foxraptor',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `foxraptor`,
		['shop'] = 'pdm',
	},
	['foxraptor'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Raptor F150 Fox',
		['brand'] = 'Ford',
		['model'] = 'foxraptor',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `foxraptor`,
		['shop'] = 'pdm',
	},
	['G632021'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'G-Class 63',
		['brand'] = 'Marcedes',
		['model'] = 'G632021',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `G632021`,
		['shop'] = 'pdm',
	},
	['jagoffroad'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Off Road Animation',
		['brand'] = 'Jaguar',
		['model'] = 'jagoffroad',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `jagoffroad`,
		['shop'] = 'pdm',
	},
	['gtz34be'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'R34 Custom Drift',
		['brand'] = 'Nissan',
		['model'] = 'gtz34be',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `gtz34be`,
		['shop'] = 'pdm',
	},
	['rs7abt'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'RS 7 ABT',
		['brand'] = 'Audi',
		['model'] = 'rs7abt',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `rs7abt`,
		['shop'] = 'pdm',
	},
	['s15mak'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'S15 Garage Mak',
		['brand'] = 'Nissan',
		['model'] = 's15mak',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `s15mak`,
		['shop'] = 'pdm',
	},
	['1m2011'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'M2 GTS',
		['brand'] = 'BMW',
		['model'] = '1m2011',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `1m2011`,
		['shop'] = 'pdm',
	},
	['2ncsgt63s'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'GT 63 S',
		['brand'] = 'Marcedes',
		['model'] = '2ncsgt63s',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `2ncsgt63s`,
		['shop'] = 'pdm',
	},
	['amggt73'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'GT 73 S',
		['brand'] = 'Marcedes',
		['model'] = 'amggt73',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `amggt73`,
		['shop'] = 'pdm',
	},
	['HellcatRed'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Hellcat',
		['brand'] = 'Dodge',
		['model'] = 'HellcatRed',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `HellcatRed`,
		['shop'] = 'pdm',
	},
	['brabusrocket900'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Rocket 900',
		['brand'] = 'Brabus',
		['model'] = 'brabusrocket900',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `brabusrocket900`,
		['shop'] = 'pdm',
	},
	['c63hr'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'C 63 HR',
		['brand'] = 'Marcedes',
		['model'] = 'c63hr',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `c63hr`,
		['shop'] = 'pdm',
	},
	['Corolax'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Corolla Rally',
		['brand'] = 'Toyota',
		['model'] = 'Corolax',
		['price'] = 221000, 	
		['category'] = 'imports',
		['hash'] = `Corolax`,
		['shop'] = 'pdm',
	},
	['fk8hr'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'FK 8 Custom',
		['brand'] = 'Honda',
		['model'] = 'fk8hr',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `fk8hr`,
		['shop'] = 'pdm',
	},
	['golfhycade'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Golf Hycade',
		['brand'] = 'VW',
		['model'] = 'golfhycade',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `golfhycade`,
		['shop'] = 'pdm',
	},
	['gti8'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'GTI 8',
		['brand'] = 'VW',
		['model'] = 'gti8',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `gti8`,
		['shop'] = 'pdm',
	},
	['huracanp'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Huraccan Custom',
		['brand'] = 'Lamborghini',
		['model'] = 'huracanp',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `huracanp`,
		['shop'] = 'pdm',
	},
	['lx570s'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'LX 570 S',
		['brand'] = 'Land Cruiser',
		['model'] = 'lx570s',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `lx570s`,
		['shop'] = 'pdm',
	},
	['m6f13'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'M6 F13',
		['brand'] = 'BMW',
		['model'] = 'm6f13',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `m6f13`,
		['shop'] = 'pdm',
	},
	['m135i'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'M1 35I',
		['brand'] = 'BMW',
		['model'] = 'm135i',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `m135i`,
		['shop'] = 'pdm',
	},
	['btype2'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Evo X',
		['brand'] = 'Mitsubishi',
		['model'] = 'btype2',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `btype2`,
		['shop'] = 'pdm',
	},
	['polestar1'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Polester Custom',
		['brand'] = 'Polestar',
		['model'] = 'polestar1',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `polestar1`,
		['shop'] = 'pdm',
	},
	['1500ghoul'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = '1500 Ghoul',
		['brand'] = 'RAM',
		['model'] = '1500ghoul',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `1500ghoul`,
		['shop'] = 'pdm',
	},
	['RS6abtp'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'RS 6 ABT',
		['brand'] = 'Audi',
		['model'] = 'RS6abtp',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `RS6abtp`,
		['shop'] = 'pdm',
	},
	['rs666'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'RS 6 Spec',
		['brand'] = 'Audi',
		['model'] = 'rs666',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `rs666`,
		['shop'] = 'pdm',
	},
	['z15326power'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'S15 ZlayWork',
		['brand'] = 'Nissan',
		['model'] = 'z15326power',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `z15326power`,
		['shop'] = 'pdm',
	},
	['sematundra'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Semathundra',
		['brand'] = 'Toyota',
		['model'] = 'sematundra',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `sematundra`,
		['shop'] = 'pdm',
	},
	['murus'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Urus',
		['brand'] = 'Lamborghini',
		['model'] = 'murus',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `murus`,
		['shop'] = 'pdm',
	},
	['murus'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'Urus',
		['brand'] = 'Lamborghini',
		['model'] = 'murus',
		['price'] = 221000, 	
		['category'] = 'customs',
		['hash'] = `murus`,
		['shop'] = 'pdm',
	},
	['bmx'] = { 	 	--DLC +set sv_enforceGameBuild 2545 
		['name'] = 'BMX',
		['brand'] = 'Bicycle',
		['model'] = 'bmx',
		['price'] = 221000, 	
		['category'] = 'locals',
		['hash'] = `bmx`,
		['shop'] = 'pdm',
	},
	['gtrlb2'] = {
		['name'] = 'GTR 34 LB',
		['brand'] = 'Nissan',
		['model'] = 'gtrlb2',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `gtrlb2`,
		['shop'] = 'pdm',
	},
	['hezo720s'] = {
		['name'] = '720s',
		['brand'] = 'Mclaren',
		['model'] = 'hezo720s',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `hezo720s`,
		['shop'] = 'pdm',
	},
	['a90e'] = {
		['name'] = 'Supra A90e',
		['brand'] = 'Toyota',
		['model'] = 'a90e',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `a90e`,
		['shop'] = 'pdm',
	},
	['s2pm'] = {
		['name'] = 'S2000 PM',
		['brand'] = 'Honda',
		['model'] = 's2pm',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `s2pm`,
		['shop'] = 'pdm',
	},
	['razersgt86'] = {
		['name'] = 'GT 86 Razer',
		['brand'] = 'Toyota',
		['model'] = 'razersgt86',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `razersgt86`,
		['shop'] = 'pdm',
	},
	['minilb'] = {
		['name'] = 'Copper LB',
		['brand'] = 'MINI',
		['model'] = 'minilb',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `minilb`,
		['shop'] = 'pdm',
	},
	['RAPTOR150'] = {
		['name'] = 'F150',
		['brand'] = 'Raptor',
		['model'] = 'RAPTOR150',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `RAPTOR150`,
		['shop'] = 'pdm',
	},
	['razerevoixdrag'] = {
		['name'] = 'Evo IX Drag',
		['brand'] = 'Mitsubishi',
		['model'] = 'razerevoixdrag',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `razerevoixdrag`,
		['shop'] = 'pdm',
	},
	['supraldc'] = {
		['name'] = 'Supda MK IV Anim',
		['brand'] = 'Toyota',
		['model'] = 'supraldc',
		['price'] = 45000,
		['category'] = 'customs',
		['hash'] = `supraldc`,
		['shop'] = 'pdm',
	},
	['e92lb'] = {
		['name'] = 'M3 Spark',
		['brand'] = 'BMW',
		['model'] = 'e92lb',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `e92lb`,
		['shop'] = 'pdm',
	},
	['h1truck'] = {
		['name'] = 'H1',
		['brand'] = 'HAMMER',
		['model'] = 'h1truck',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `h1truck`,
		['shop'] = 'pdm',
	},
	['h1truck'] = {
		['name'] = 'H1',
		['brand'] = 'HAMMER',
		['model'] = 'h1truck',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `h1truck`,
		['shop'] = 'pdm',
	},
	['semaevo'] = {
		['name'] = 'Lance Sema Evo',
		['brand'] = 'Mitsubishi',
		['model'] = 'semaevo',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `semaevo`,
		['shop'] = 'pdm',
	},
	['semaevo'] = {
		['name'] = 'Lance Sema Evo',
		['brand'] = 'Mitsubishi',
		['model'] = 'semaevo',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `semaevo`,
		['shop'] = 'pdm',
	},
	['mlec'] = {
		['name'] = 'Evo CLinced',
		['brand'] = 'Mitsubishi',
		['model'] = 'mlec',
		['price'] = 45000,
		['category'] = 'customs',
		['hash'] = `mlec`,
		['shop'] = 'pdm',
	},
	['mlec'] = {
		['name'] = 'Evo CLinced',
		['brand'] = 'Mitsubishi',
		['model'] = 'mlec',
		['price'] = 45000,
		['category'] = 'customs',
		['hash'] = `mlec`,
		['shop'] = 'pdm',
	},
	['evoxx'] = {
		['name'] = 'Evo Speed Hunter',
		['brand'] = 'Mitsubishi',
		['model'] = 'evoxx',
		['price'] = 45000,
		['category'] = 'customs',
		['hash'] = `evoxx`,
		['shop'] = 'pdm',
	},
	['kiethford'] = {
		['name'] = 'Ford F150 Drag',
		['brand'] = 'Ford',
		['model'] = 'kiethford',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `kiethford`,
		['shop'] = 'pdm',
	},
	['kiethford'] = {
		['name'] = 'Ford F150 Drag',
		['brand'] = 'Ford',
		['model'] = 'kiethford',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `kiethford`,
		['shop'] = 'pdm',
	},
	['fd370z'] = {
		['name'] = 'FD 370z',
		['brand'] = 'Nissan',
		['model'] = 'fd370z',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `fd370z`,
		['shop'] = 'pdm',
	},
	['fd370z'] = {
		['name'] = 'FD 370z',
		['brand'] = 'Nissan',
		['model'] = 'fd370z',
		['price'] = 45000,
		['category'] = 'imports',
		['hash'] = `fd370z`,
		['shop'] = 'pdm',
	},
		-- Boats
	['squalo'] = {
		['name'] = 'Squalo',
		['brand'] = 'Shitzu',
		['model'] = 'squalo',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `squalo`,
		['shop'] = 'boats',
	},
	['marquis'] = {
		['name'] = 'Marquis',
		['brand'] = 'Dinka',
		['model'] = 'marquis',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `marquis`,
		['shop'] = 'boats',
	},
	['seashark'] = {
		['name'] = 'Seashark',
		['brand'] = 'Speedophile',
		['model'] = 'seashark',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `seashark`,
		['shop'] = 'boats',
	},
	['seashark2'] = {
		['name'] = 'Seashark',
		['brand'] = 'Speedophile',
		['model'] = 'seashark2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `seashark2`,
		['shop'] = 'boats',
	},
	['seashark3'] = {
		['name'] = 'Seashark',
		['brand'] = 'Speedophile',
		['model'] = 'seashark3',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `seashark3`,
		['shop'] = 'boats',
	},
	['jetmax'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Jetmax',
		['model'] = 'jetmax',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `jetmax`,
		['shop'] = 'boats',
	},
	['tropic'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Tropic',
		['model'] = 'tropic',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `tropic`,
		['shop'] = 'boats',
	},
	['tropic2'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Tropic',
		['model'] = 'tropic2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `tropic2`,
		['shop'] = 'boats',
	},
	['dinghy'] = {
		['name'] = 'Nagasaki',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `dinghy`,
		['shop'] = 'boats',
	},
	['dinghy2'] = {
		['name'] = 'Nagasaki',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `dinghy2`,
		['shop'] = 'boats',
	},
	['dinghy3'] = {
		['name'] = 'Nagasaki',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy3',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `dinghy3`,
		['shop'] = 'boats',
	},
	['dinghy4'] = {
		['name'] = 'Nagasaki',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy4',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `dinghy4`,
		['shop'] = 'boats',
	},
	['suntrap'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Suntrap',
		['model'] = 'suntrap',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `suntrap`,
		['shop'] = 'boats',
	},
	['speeder'] = {
		['name'] = 'Speeder',
		['brand'] = 'Pegassi',
		['model'] = 'speeder',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `speeder`,
		['shop'] = 'boats',
	},
	['speeder2'] = {
		['name'] = 'Speeder',
		['brand'] = 'Pegassi',
		['model'] = 'speeder2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `speeder2`,
		['shop'] = 'boats',
	},
	['longfin'] = {
		['name'] = 'Longfin',
		['brand'] = 'Shitzu',
		['model'] = 'longfin',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `longfin`,
		['shop'] = 'boats',
	},
	['toro'] = {
		['name'] = 'Toro',
		['brand'] = 'Lampadati',
		['model'] = 'toro',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `toro`,
		['shop'] = 'boats',
	},
	['toro2'] = {
		['name'] = 'Toro',
		['brand'] = 'Lampadati',
		['model'] = 'toro2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `toro2`,
		['shop'] = 'boats',
	},
	-- helicopters
	['buzzard2'] = {
		['name'] = 'Buzzard',
		['brand'] = 'Unknown',
		['model'] = 'buzzard2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `buzzard2`,
		['shop'] = 'air',
	},
	['frogger'] = {
		['name'] = 'Frogger',
		['brand'] = 'Unknown',
		['model'] = 'frogger',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `frogger`,
		['shop'] = 'air',
	},
	['frogger2'] = {
		['name'] = 'Frogger',
		['brand'] = 'Unknown',
		['model'] = 'frogger2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `frogger2`,
		['shop'] = 'air',
	},
	['maverick'] = {
		['name'] = 'Maverick',
		['brand'] = 'Unknown',
		['model'] = 'maverick',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `maverick`,
		['shop'] = 'air',
	},
	['swift'] = {
		['name'] = 'Swift',
		['brand'] = 'Buckingham',
		['model'] = 'swift',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `swift`,
		['shop'] = 'air',
	},
	['swift2'] = {
		['name'] = 'Swift',
		['brand'] = 'Buckingham',
		['model'] = 'swift2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `swift2`,
		['shop'] = 'air',
	},
	['seasparrow'] = {
		['name'] = 'Sea Sparrow',
		['brand'] = 'Unknown',
		['model'] = 'seasparrow',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `seasparrow`,
		['shop'] = 'air',
	},
	['seasparrow2'] = {
		['name'] = 'Sparrow',
		['brand'] = 'Unknown',
		['model'] = 'seasparrow2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `seasparrow2`,
		['shop'] = 'air',
	},
	['seasparrow3'] = {
		['name'] = 'Sparrow',
		['brand'] = 'Unknown',
		['model'] = 'seasparrow3',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `seasparrow3`,
		['shop'] = 'air',
	},
	['supervolito'] = {
		['name'] = 'SuperVolito',
		['brand'] = 'Buckingham',
		['model'] = 'supervolito',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `supervolito`,
		['shop'] = 'air',
	},
	['supervolito2'] = {
		['name'] = 'SuperVolito Carbon',
		['brand'] = 'Buckingham',
		['model'] = 'supervolito2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `supervolito2`,
		['shop'] = 'air',
	},
	['volatus'] = {
		['name'] = 'Volatus',
		['brand'] = 'Buckingham',
		['model'] = 'volatus',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `volatus`,
		['shop'] = 'air',
	},
	['havok'] = {
		['name'] = 'Havok',
		['brand'] = 'Nagasaki',
		['model'] = 'havok',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `havok`,
		['shop'] = 'air',
	},
	-- Planes
	['duster'] = {
		['name'] = 'Duster',
		['brand'] = 'Unknown',
		['model'] = 'duster',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `duster`,
		['shop'] = 'air',
	},
	['luxor'] = {
		['name'] = 'Luxor',
		['brand'] = 'Buckingham',
		['model'] = 'luxor',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `luxor`,
		['shop'] = 'air',
	},
	['luxor2'] = {
		['name'] = 'Luxor Deluxe',
		['brand'] = 'Buckingham',
		['model'] = 'luxor2',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `luxor2`,
		['shop'] = 'air',
	},
	['stunt'] = {
		['name'] = 'Mallard',
		['brand'] = 'Unknown',
		['model'] = 'stunt',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `stunt`,
		['shop'] = 'air',
	},
	['mammatus'] = {
		['name'] = 'Mammatus',
		['brand'] = 'Unknown',
		['model'] = 'mammatus',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `mammatus`,
		['shop'] = 'air',
	},
	['velum'] = {
		['name'] = 'Velum',
		['brand'] = 'Unknown',
		['model'] = 'velum',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `velum`,
		['shop'] = 'air',
	},
	['velum2'] = {
		['name'] = 'Velum',
		['brand'] = 'Unknown',
		['model'] = 'velum2',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `velum2`,
		['shop'] = 'air',
	},
	['shamal'] = {
		['name'] = 'Shamal',
		['brand'] = 'Buckingham',
		['model'] = 'shamal',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `shamal`,
		['shop'] = 'air',
	},
	['vestra'] = {
		['name'] = 'Vestra',
		['brand'] = 'Buckingham',
		['model'] = 'vestra',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `vestra`,
		['shop'] = 'air',
	},
	['dodo'] = {
		['name'] = 'Dodo',
		['brand'] = 'Mammoth',
		['model'] = 'dodo',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `dodo`,
		['shop'] = 'air',
	},
	['howard'] = {
		['name'] = 'Howard NX-25',
		['brand'] = 'Buckingham',
		['model'] = 'howard',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `howard`,
		['shop'] = 'air',
	},
	['alphaz1'] = {
		['name'] = 'Alpha-Z1',
		['brand'] = 'Buckingham',
		['model'] = 'alphaz1',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `alphaz1`,
		['shop'] = 'air',
	},
	['nimbus'] = {
		['name'] = 'Nimbus',
		['brand'] = 'Buckingham',
		['model'] = 'nimbus',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `nimbus`,
		['shop'] = 'air',
	},
	
}
